name: macOS
on:
  push:
    branches:
    - "main"
    - "core-8-branch"
    - "core-8-6-branch"
    - "bug-22349fc78a-v2"
    tags:
    - "core-**"
permissions:
  contents: read
#env:
#  ERROR_ON_FAILURES: 1
jobs:
  xcode:
    runs-on: macos-12
    defaults:
      run:
        shell: bash
        working-directory: tk/macosx
    steps:
      - name: Checkout Tk
        uses: actions/checkout@v4
        with:
          path: tk
      - name: Checkout Tcl
        uses: actions/checkout@v4
        with:
          repository: tcltk/tcl
          ref: core-8-6-branch
          path: tcl
      - name: Prepare checked out repositories
        run: |
          touch tk/generic/tkStubInit.c
          mkdir build
          echo "BUILD_DIR=`cd build && pwd`" >> $GITHUB_ENV
          echo "DESTDIR=`cd build && pwd`" >> $GITHUB_ENV
        working-directory: .
      - name: Build Tcl
        run: |
          make all
        working-directory: tcl/macosx
      - name: Build
        run: |
          make all install || {
            echo "::error::Failure during Build"
          }
      - name: Run Tests
        run: |
          make TESTFLAGS="-verbose bpest" test | tee out.txt
          nmatches=$( grep -c "Failed	0" out.txt )
          if [ $nmatches -lt 4 ]
          then
            echo "::error::Failure during Test"
          fi
        timeout-minutes: 30
      - name: Get crash report
        run: |
          mkdir ~/crashes
          cp ~/Library/Logs/DiagnosticReports/tktest* crashes
      - name: Upload crash reports
        uses: actions/upload-artifact@v3
        with:
          name: Logfiles
          path: ~/crashes
